[2024-12-04T13:13:17.832+0700] {processor.py:186} INFO - Started process (PID=17044) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:13:17.833+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T13:13:17.839+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:13:17.838+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:13:17.845+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:13:17.844+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T13:13:17.845+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:13:17.845+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T13:13:17.845+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:13:17.856+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-12-04T13:32:34.372+0700] {processor.py:186} INFO - Started process (PID=30716) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:32:34.374+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T13:32:34.377+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:32:34.376+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:32:34.380+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:32:34.380+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T13:32:34.380+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:32:34.380+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T13:32:34.381+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:32:34.391+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-12-04T13:33:30.288+0700] {processor.py:186} INFO - Started process (PID=30921) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:33:30.290+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T13:33:30.292+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:33:30.292+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:33:30.296+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:33:30.296+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T13:33:30.296+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:33:30.296+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T13:33:30.297+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:33:30.307+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-12-04T13:34:28.385+0700] {processor.py:186} INFO - Started process (PID=31174) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:34:28.387+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T13:34:28.389+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:34:28.388+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:34:28.396+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:34:28.394+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T13:34:28.397+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:34:28.397+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T13:34:28.397+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:34:28.410+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-12-04T13:35:28.288+0700] {processor.py:186} INFO - Started process (PID=31483) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:35:28.289+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T13:35:28.292+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:35:28.291+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:35:28.299+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:35:28.296+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T13:35:28.299+0700] {logging_mixin.py:190} INFO - [2024-12-04T13:35:28.299+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T13:35:28.299+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T13:35:28.311+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-12-04T14:10:10.702+0700] {processor.py:186} INFO - Started process (PID=37461) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:10:10.705+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:10:10.712+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:10:10.711+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:10:10.722+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:10:10.720+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:10:10.723+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:10:10.723+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:10:10.724+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:10:10.764+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2024-12-04T14:11:21.927+0700] {processor.py:186} INFO - Started process (PID=37802) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:11:21.929+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:11:21.934+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:11:21.933+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:11:21.943+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:11:21.941+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:11:21.944+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:11:21.944+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:11:21.944+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:11:21.966+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2024-12-04T14:40:28.796+0700] {processor.py:186} INFO - Started process (PID=45675) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:40:28.798+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:40:28.804+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:40:28.803+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:40:28.813+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:40:28.811+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:40:28.814+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:40:28.814+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:40:28.815+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:40:28.900+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2024-12-04T14:40:59.187+0700] {processor.py:186} INFO - Started process (PID=45954) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:40:59.189+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:40:59.195+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:40:59.194+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:40:59.207+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:40:59.204+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:40:59.208+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:40:59.208+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:40:59.209+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:40:59.277+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
[2024-12-04T14:41:30.120+0700] {processor.py:186} INFO - Started process (PID=46252) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:41:30.123+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:41:30.128+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:41:30.128+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:41:30.137+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:41:30.134+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:41:30.138+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:41:30.138+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:41:30.139+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:41:30.204+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-12-04T14:42:01.159+0700] {processor.py:186} INFO - Started process (PID=46560) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:42:01.162+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:42:01.172+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:42:01.170+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:42:01.191+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:42:01.182+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:42:01.192+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:42:01.192+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:42:01.192+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:42:01.290+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.156 seconds
[2024-12-04T14:42:31.974+0700] {processor.py:186} INFO - Started process (PID=47022) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:42:31.978+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:42:31.985+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:42:31.984+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:42:31.995+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:42:31.992+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:42:31.995+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:42:31.995+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:42:31.996+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:42:32.048+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-12-04T14:43:03.038+0700] {processor.py:186} INFO - Started process (PID=47614) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:43:03.039+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:43:03.044+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:43:03.043+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:43:03.050+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:43:03.049+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:43:03.051+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:43:03.050+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:43:03.051+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:43:03.096+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-12-04T14:43:33.598+0700] {processor.py:186} INFO - Started process (PID=47771) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:43:33.609+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:43:33.616+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:43:33.615+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:43:33.666+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:43:33.651+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:43:33.667+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:43:33.667+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:43:33.668+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:43:33.779+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.227 seconds
[2024-12-04T14:44:04.365+0700] {processor.py:186} INFO - Started process (PID=47898) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:44:04.367+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:44:04.372+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:44:04.371+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:44:04.381+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:44:04.380+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:44:04.382+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:44:04.382+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:44:04.382+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:44:04.429+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2024-12-04T14:44:35.241+0700] {processor.py:186} INFO - Started process (PID=48036) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:44:35.244+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:44:35.251+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:44:35.250+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:44:35.265+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:44:35.263+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:44:35.269+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:44:35.268+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:44:35.269+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:44:35.339+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.120 seconds
[2024-12-04T14:45:05.582+0700] {processor.py:186} INFO - Started process (PID=48906) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:45:05.586+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:45:05.593+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:45:05.592+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:45:05.617+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:45:05.610+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:45:05.621+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:45:05.620+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:45:05.622+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:45:05.695+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.159 seconds
[2024-12-04T14:45:35.818+0700] {processor.py:186} INFO - Started process (PID=49705) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:45:35.820+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:45:35.826+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:45:35.825+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:45:35.840+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:45:35.834+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:45:35.843+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:45:35.842+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:45:35.844+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:45:35.949+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.149 seconds
[2024-12-04T14:46:08.230+0700] {processor.py:186} INFO - Started process (PID=50401) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:46:08.261+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:46:08.289+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:46:08.284+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:46:08.412+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:46:08.399+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:46:08.414+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:46:08.413+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:46:08.415+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:46:08.546+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.439 seconds
[2024-12-04T14:46:40.675+0700] {processor.py:186} INFO - Started process (PID=51190) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:46:40.677+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:46:40.696+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:46:40.690+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:46:40.728+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:46:40.716+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:46:40.729+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:46:40.729+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:46:40.729+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:46:40.800+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.150 seconds
[2024-12-04T14:47:11.255+0700] {processor.py:186} INFO - Started process (PID=51671) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:47:11.257+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:47:11.263+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:47:11.262+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:47:11.272+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:47:11.270+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:47:11.273+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:47:11.273+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:47:11.274+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:47:11.335+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2024-12-04T14:47:42.624+0700] {processor.py:186} INFO - Started process (PID=52201) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:47:42.627+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:47:42.633+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:47:42.632+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:47:42.644+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:47:42.642+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:47:42.645+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:47:42.645+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:47:42.646+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:47:42.723+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2024-12-04T14:48:12.908+0700] {processor.py:186} INFO - Started process (PID=52552) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:48:12.918+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:48:12.925+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:48:12.924+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:48:12.955+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:48:12.935+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:48:12.956+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:48:12.956+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:48:12.957+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:48:13.112+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.226 seconds
[2024-12-04T14:48:44.009+0700] {processor.py:186} INFO - Started process (PID=52971) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:48:44.012+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:48:44.019+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:48:44.018+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:48:44.038+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:48:44.034+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:48:44.041+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:48:44.039+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:48:44.042+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:48:44.148+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.160 seconds
[2024-12-04T14:49:14.964+0700] {processor.py:186} INFO - Started process (PID=53342) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:49:14.972+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:49:14.981+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:49:14.980+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:49:14.992+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:49:14.991+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:49:14.994+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:49:14.993+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:49:14.994+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:49:15.210+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.265 seconds
[2024-12-04T14:49:49.292+0700] {processor.py:186} INFO - Started process (PID=54013) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:49:49.310+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:49:49.322+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:49:49.316+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:49:49.333+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:49:49.331+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:49:49.338+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:49:49.335+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:49:49.340+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:49:49.458+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.215 seconds
[2024-12-04T14:50:26.803+0700] {processor.py:186} INFO - Started process (PID=55044) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:50:26.816+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:50:26.826+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:50:26.825+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:50:26.885+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:50:26.866+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:50:26.886+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:50:26.886+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:50:26.886+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:50:27.008+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.316 seconds
[2024-12-04T14:50:57.539+0700] {processor.py:186} INFO - Started process (PID=55888) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:50:57.545+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:50:57.548+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:50:57.547+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:50:57.557+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:50:57.555+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:50:57.558+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:50:57.557+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:50:57.558+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:50:57.746+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.262 seconds
[2024-12-04T14:51:28.356+0700] {processor.py:186} INFO - Started process (PID=56785) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:51:28.367+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:51:28.378+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:51:28.377+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:51:28.430+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:51:28.422+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:51:28.431+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:51:28.431+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:51:28.431+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:51:28.573+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.270 seconds
[2024-12-04T14:52:00.069+0700] {processor.py:186} INFO - Started process (PID=57646) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:52:00.100+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:52:00.103+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:52:00.102+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:52:00.156+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:52:00.155+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:52:00.172+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:52:00.171+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:52:00.173+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:52:00.333+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.324 seconds
[2024-12-04T14:52:31.688+0700] {processor.py:186} INFO - Started process (PID=58201) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:52:31.708+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:52:31.713+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:52:31.712+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:52:31.784+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:52:31.743+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:52:31.785+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:52:31.785+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:52:31.785+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:52:32.002+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.367 seconds
[2024-12-04T14:53:02.551+0700] {processor.py:186} INFO - Started process (PID=58868) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:53:02.564+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:53:02.571+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:53:02.570+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:53:02.621+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:53:02.595+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:53:02.622+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:53:02.622+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:53:02.625+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:53:02.805+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.305 seconds
[2024-12-04T14:53:34.526+0700] {processor.py:186} INFO - Started process (PID=59691) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:53:34.530+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:53:34.550+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:53:34.533+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:53:34.587+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:53:34.576+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:53:34.588+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:53:34.587+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:53:34.588+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:53:34.711+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.293 seconds
[2024-12-04T14:54:09.387+0700] {processor.py:186} INFO - Started process (PID=60903) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:54:09.407+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:54:09.411+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:54:09.410+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:54:09.437+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:54:09.419+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:54:09.439+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:54:09.439+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:54:09.441+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:54:09.624+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.276 seconds
[2024-12-04T14:54:41.995+0700] {processor.py:186} INFO - Started process (PID=61762) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:54:41.997+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:54:42.000+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:54:41.999+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:54:42.033+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:54:42.028+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:54:42.034+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:54:42.034+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:54:42.035+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:54:42.126+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.205 seconds
[2024-12-04T14:55:14.187+0700] {processor.py:186} INFO - Started process (PID=62451) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:55:14.195+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:55:14.206+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:55:14.198+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:55:14.238+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:55:14.218+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:55:14.239+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:55:14.239+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:55:14.240+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:55:14.403+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.249 seconds
[2024-12-04T14:55:45.702+0700] {processor.py:186} INFO - Started process (PID=63121) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:55:45.708+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:55:45.718+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:55:45.717+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:55:45.779+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:55:45.777+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:55:45.781+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:55:45.780+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:55:45.793+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:55:45.932+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.252 seconds
[2024-12-04T14:56:16.445+0700] {processor.py:186} INFO - Started process (PID=63890) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:56:16.447+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:56:16.449+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:56:16.448+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:56:16.476+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:56:16.466+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:56:16.477+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:56:16.477+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:56:16.478+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:56:16.560+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.146 seconds
[2024-12-04T14:56:46.969+0700] {processor.py:186} INFO - Started process (PID=64674) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:56:46.977+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:56:46.982+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:56:46.981+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:56:47.000+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:56:46.993+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:56:47.001+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:56:47.000+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:56:47.001+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:56:47.065+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
[2024-12-04T14:57:18.888+0700] {processor.py:186} INFO - Started process (PID=65447) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:57:18.901+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:57:18.907+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:57:18.906+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:57:18.923+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:57:18.921+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:57:18.934+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:57:18.933+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:57:18.938+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:57:19.097+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.230 seconds
[2024-12-04T14:57:49.669+0700] {processor.py:186} INFO - Started process (PID=66148) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:57:49.672+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:57:49.675+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:57:49.675+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:57:49.683+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:57:49.681+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:57:49.684+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:57:49.683+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:57:49.685+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:57:49.782+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.127 seconds
[2024-12-04T14:58:20.165+0700] {processor.py:186} INFO - Started process (PID=67013) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:58:20.166+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:58:20.169+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:58:20.168+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:58:20.175+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:58:20.174+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:58:20.175+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:58:20.175+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:58:20.176+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:58:20.223+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-12-04T14:58:50.810+0700] {processor.py:186} INFO - Started process (PID=67780) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:58:50.811+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:58:50.813+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:58:50.813+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:58:50.818+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:58:50.817+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:58:50.818+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:58:50.818+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:58:50.819+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:58:50.853+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-12-04T14:59:22.339+0700] {processor.py:186} INFO - Started process (PID=68867) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:59:22.347+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:59:22.377+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:59:22.373+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:59:22.453+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:59:22.430+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:59:22.454+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:59:22.453+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:59:22.454+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:59:22.520+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.483 seconds
[2024-12-04T14:59:55.081+0700] {processor.py:186} INFO - Started process (PID=69961) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:59:55.094+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T14:59:55.096+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:59:55.095+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:59:55.159+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:59:55.133+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T14:59:55.163+0700] {logging_mixin.py:190} INFO - [2024-12-04T14:59:55.160+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T14:59:55.164+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T14:59:55.534+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.485 seconds
[2024-12-04T15:00:25.748+0700] {processor.py:186} INFO - Started process (PID=71295) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:00:25.762+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:00:25.764+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:00:25.764+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:00:25.795+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:00:25.794+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:00:25.796+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:00:25.795+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:00:25.796+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:00:25.867+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.155 seconds
[2024-12-04T15:01:42.056+0700] {processor.py:186} INFO - Started process (PID=73530) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:01:42.077+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:01:42.093+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:01:42.085+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:01:42.136+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:01:42.131+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:01:42.137+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:01:42.137+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:01:42.138+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:01:42.314+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.311 seconds
[2024-12-04T15:02:12.762+0700] {processor.py:186} INFO - Started process (PID=74912) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:02:12.779+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:02:12.832+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:02:12.831+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:02:12.995+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:02:12.924+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:02:12.996+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:02:12.995+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:02:12.997+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:02:13.270+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.588 seconds
[2024-12-04T15:02:46.081+0700] {processor.py:186} INFO - Started process (PID=75928) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:02:46.099+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:02:46.103+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:02:46.102+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:02:46.127+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:02:46.126+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:02:46.137+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:02:46.136+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:02:46.140+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:02:46.291+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2024-12-04T15:03:16.522+0700] {processor.py:186} INFO - Started process (PID=77205) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:03:16.534+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:03:16.548+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:03:16.548+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:03:16.555+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:03:16.554+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:03:16.562+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:03:16.561+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:03:16.562+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:03:16.755+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.264 seconds
[2024-12-04T15:03:50.074+0700] {processor.py:186} INFO - Started process (PID=78286) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:03:50.095+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:03:50.098+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:03:50.097+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:03:50.140+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:03:50.126+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:03:50.141+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:03:50.141+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:03:50.141+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:03:50.219+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.227 seconds
[2024-12-04T15:04:20.569+0700] {processor.py:186} INFO - Started process (PID=79328) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:04:20.578+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:04:20.580+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:04:20.579+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:04:20.604+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:04:20.602+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:04:20.604+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:04:20.604+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:04:20.605+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:04:20.699+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.153 seconds
[2024-12-04T15:04:53.220+0700] {processor.py:186} INFO - Started process (PID=80514) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:04:53.224+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:04:53.227+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:04:53.227+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:04:53.310+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:04:53.253+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:04:53.310+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:04:53.310+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:04:53.311+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:04:53.415+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.239 seconds
[2024-12-04T15:05:34.363+0700] {processor.py:186} INFO - Started process (PID=81800) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:05:34.384+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:05:34.430+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:05:34.415+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:05:34.506+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:05:34.489+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:05:34.514+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:05:34.513+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:05:34.530+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:05:34.723+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.522 seconds
[2024-12-04T15:06:06.580+0700] {processor.py:186} INFO - Started process (PID=82595) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:06:06.586+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:06:06.592+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:06:06.591+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:06:06.618+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:06:06.611+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:06:06.619+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:06:06.618+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:06:06.619+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:06:06.814+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.282 seconds
[2024-12-04T15:06:37.635+0700] {processor.py:186} INFO - Started process (PID=83471) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:06:37.648+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:06:37.666+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:06:37.665+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:06:37.682+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:06:37.681+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:06:37.708+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:06:37.708+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:06:37.712+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:06:37.825+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.235 seconds
[2024-12-04T15:07:09.069+0700] {processor.py:186} INFO - Started process (PID=84359) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:07:09.086+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:07:09.092+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:07:09.092+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:07:09.104+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:07:09.103+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:07:09.105+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:07:09.105+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:07:09.105+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:07:09.298+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.299 seconds
[2024-12-04T15:07:40.796+0700] {processor.py:186} INFO - Started process (PID=85247) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:07:40.799+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:07:40.801+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:07:40.801+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:07:40.857+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:07:40.855+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:07:40.857+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:07:40.857+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:07:40.858+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:07:41.176+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.454 seconds
[2024-12-04T15:08:12.231+0700] {processor.py:186} INFO - Started process (PID=86102) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:08:12.248+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:08:12.251+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:08:12.250+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:08:12.277+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:08:12.270+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:08:12.278+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:08:12.278+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:08:12.279+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:08:12.360+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.158 seconds
[2024-12-04T15:08:43.929+0700] {processor.py:186} INFO - Started process (PID=86890) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:08:43.934+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:08:43.940+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:08:43.936+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:08:43.981+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:08:43.965+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:08:43.982+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:08:43.982+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:08:43.983+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:08:44.134+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.220 seconds
[2024-12-04T15:09:15.334+0700] {processor.py:186} INFO - Started process (PID=87735) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:09:15.353+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:09:15.371+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:09:15.370+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:09:15.410+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:09:15.408+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:09:15.410+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:09:15.410+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:09:15.410+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:09:15.502+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.211 seconds
[2024-12-04T15:09:47.750+0700] {processor.py:186} INFO - Started process (PID=88656) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:09:47.758+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:09:47.770+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:09:47.769+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:09:47.841+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:09:47.822+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:09:47.842+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:09:47.841+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:09:47.842+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:09:48.066+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.377 seconds
[2024-12-04T15:10:23.142+0700] {processor.py:186} INFO - Started process (PID=89540) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:10:23.158+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:10:23.229+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:10:23.164+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:10:23.427+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:10:23.375+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:10:23.428+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:10:23.428+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:10:23.429+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:10:24.063+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.052 seconds
[2024-12-04T15:10:59.271+0700] {processor.py:186} INFO - Started process (PID=90472) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:10:59.312+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:10:59.324+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:10:59.323+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:10:59.395+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:10:59.382+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:10:59.401+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:10:59.401+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:10:59.405+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:10:59.554+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.426 seconds
[2024-12-04T15:11:46.035+0700] {processor.py:186} INFO - Started process (PID=91681) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:11:46.042+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:11:46.062+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:11:46.061+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:11:46.179+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:11:46.178+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:11:46.180+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:11:46.180+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:11:46.181+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:11:46.760+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.790 seconds
[2024-12-04T15:12:32.143+0700] {processor.py:186} INFO - Started process (PID=93211) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:12:32.186+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:12:32.193+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:12:32.191+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:12:32.283+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:12:32.278+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:12:32.284+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:12:32.284+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:12:32.285+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:12:32.555+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.522 seconds
[2024-12-04T15:13:08.203+0700] {processor.py:186} INFO - Started process (PID=94357) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:13:08.207+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:13:08.210+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:13:08.209+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:13:08.253+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:13:08.251+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:13:08.256+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:13:08.255+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:13:08.257+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:13:08.432+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.256 seconds
[2024-12-04T15:13:41.733+0700] {processor.py:186} INFO - Started process (PID=95284) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:13:41.768+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:13:41.806+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:13:41.805+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:13:41.836+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:13:41.835+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:13:41.877+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:13:41.876+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:13:41.880+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:13:42.177+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.503 seconds
[2024-12-04T15:14:21.459+0700] {processor.py:186} INFO - Started process (PID=96557) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:14:21.466+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:14:21.492+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:14:21.492+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:14:21.531+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:14:21.516+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:14:21.544+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:14:21.543+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:14:21.580+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:14:21.744+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.353 seconds
[2024-12-04T15:15:09.057+0700] {processor.py:186} INFO - Started process (PID=98353) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:15:09.060+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:15:09.068+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:15:09.067+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:15:09.094+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:15:09.093+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:15:09.096+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:15:09.095+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:15:09.097+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:15:09.226+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.228 seconds
[2024-12-04T15:15:55.989+0700] {processor.py:186} INFO - Started process (PID=99455) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:15:55.997+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:15:56.019+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:15:56.018+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:15:56.047+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:15:56.039+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:15:56.049+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:15:56.049+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:15:56.054+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:15:56.163+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.474 seconds
[2024-12-04T15:16:49.953+0700] {processor.py:186} INFO - Started process (PID=100886) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:16:49.957+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:16:49.960+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:16:49.959+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:16:49.969+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:16:49.968+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:16:49.970+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:16:49.970+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:16:49.970+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:16:50.149+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.317 seconds
[2024-12-04T15:17:41.500+0700] {processor.py:186} INFO - Started process (PID=102985) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:17:41.593+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:17:41.595+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:17:41.595+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:17:41.613+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:17:41.612+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:17:41.618+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:17:41.617+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:17:41.619+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:17:41.730+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.389 seconds
[2024-12-04T15:18:33.301+0700] {processor.py:186} INFO - Started process (PID=104894) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:18:33.318+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:18:33.337+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:18:33.333+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:18:33.409+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:18:33.392+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:18:33.412+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:18:33.411+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:18:33.415+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:18:33.573+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.415 seconds
[2024-12-04T15:19:37.205+0700] {processor.py:186} INFO - Started process (PID=106611) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:19:37.221+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:19:37.223+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:19:37.223+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:19:37.278+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:19:37.277+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:19:37.453+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:19:37.278+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:19:37.454+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:19:38.323+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.526 seconds
[2024-12-04T15:20:27.049+0700] {processor.py:186} INFO - Started process (PID=108382) to work on /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:20:27.066+0700] {processor.py:914} INFO - Processing file /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-04T15:20:27.069+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:20:27.068+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:20:27.103+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:20:27.102+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-04T15:20:27.122+0700] {logging_mixin.py:190} INFO - [2024-12-04T15:20:27.121+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-04T15:20:27.123+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-04T15:20:27.504+0700] {processor.py:208} INFO - Processing /home/dea/weather-monitoring/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.518 seconds
